import { useEffect, useMemo, useState } from 'react';
import { createAnalysis, listAnalysis } from '../services/analysisService';
import type { Analysis, BuyDecision } from '../types/analysis';

export default function AnalysisImpl() {
  const [rows, setRows] = useState<Analysis[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [f, setF] = useState({ user_id: 1, stock_symbol: '', stock_price: 0, risk_price: 0, reward_price: 0, buy_decision: 'WAIT' as BuyDecision, notes: '' });
  const load = async () => { setLoading(true); try { setRows(await listAnalysis()); setError(''); } catch (e) { console.error(e); setError('Unable to load analysis'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const m = useMemo(() => { const risk = f.stock_price - f.risk_price; const reward = f.reward_price - f.stock_price; return { risk, reward, riskPct: f.stock_price ? (risk / f.stock_price) * 100 : 0, rewardPct: f.stock_price ? (reward / f.stock_price) * 100 : 0, rr: risk > 0 ? reward / risk : 0 }; }, [f]);
  return <section className='space-y-6'><h1 className='text-2xl font-semibold'>Analysis</h1>{error && <div className='rounded-xl bg-red-50 p-3 text-sm text-red-600'>{error}</div>}
  <div className='grid gap-4 lg:grid-cols-2'><div className='rounded-2xl border bg-white p-4 shadow-sm space-y-3'>{[['Stock Symbol','stock_symbol','text'],['Stock Price','stock_price','number'],['Risk Price','risk_price','number'],['Reward Price','reward_price','number']].map(([label,key,type])=><label key={key} className='block text-sm'><span>{label}</span><input type={type} className='mt-1 w-full rounded-xl border p-2' onChange={e=>setF({...f,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>)}<label className='block text-sm'>Decision<select className='mt-1 w-full rounded-xl border p-2' onChange={e=>setF({...f,buy_decision:e.target.value as BuyDecision})}><option>BUY</option><option>WAIT</option><option>AVOID</option></select></label><label className='block text-sm'>Notes<textarea className='mt-1 w-full rounded-xl border p-2' rows={3} onChange={e=>setF({...f,notes:e.target.value})} /></label><input type='file' multiple className='text-sm' /><button className='rounded-xl bg-indigo-600 px-4 py-2 text-white' onClick={async()=>{try{await createAnalysis(f);await load();}catch(e){console.error(e);setError('Failed to save analysis');}}}>Save Analysis</button></div>
  <div className='grid gap-3 sm:grid-cols-2'>{[['Risk Amount',m.risk,'text-red-600'],['Reward Amount',m.reward,'text-emerald-600'],['Risk %',m.riskPct,'text-red-600'],['Reward %',m.rewardPct,'text-emerald-600'],['RR Ratio',m.rr,'text-indigo-600']].map(([t,v,c])=><div key={String(t)} className='rounded-2xl border bg-white p-4 shadow-sm'><p className='text-xs text-slate-500'>{t}</p><p className={`text-xl font-semibold ${c}`}>{Number(v).toFixed(2)}</p></div>)}</div></div>
  <div className='rounded-2xl border bg-white p-4 shadow-sm overflow-auto'><h2 className='mb-3 font-semibold'>Analysis History</h2>{loading?<div className='h-24 animate-pulse rounded bg-slate-100'/>:<table className='min-w-full text-sm'><thead><tr className='text-left text-slate-500'><th>Stock</th><th>Price</th><th>Risk</th><th>Reward</th><th>RR</th><th>Decision</th><th>Date</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className='border-t hover:bg-slate-50'><td className='py-2'>{r.stock_symbol}</td><td>{r.stock_price}</td><td>{r.risk_price}</td><td>{r.reward_price}</td><td>{((r.reward_price-r.stock_price)/((r.stock_price-r.risk_price)||1)).toFixed(2)}</td><td><span className='rounded-full bg-slate-100 px-2 py-1 text-xs'>{r.buy_decision}</span></td><td>{r.created_at?.slice(0,10)}</td></tr>)}</tbody></table>}{!loading&&rows.length===0&&<div className='py-10 text-center'><p className='font-medium'>No analysis yet</p><p className='text-sm text-slate-500'>Create your first analysis to populate this table.</p></div>}</div></section>;
}
